In [98]:
import numpy as np

B = np.array([[1,0,0],[0,1,0],[0,0,1]])
N = np.array([[-3,2],[-1,2],[1,1]])

B_inv = np.linalg.inv(B)

CB = np.array([[0,0,0]])
CN = np.array([[-1,-2]])

b = np.array([[2],[4],[5]])

b_barre = B_inv.dot(b)

#b_barre
#CN.shape
#B_inv.shape
pi = CB.dot(B_inv)
pi.shape
CN_barre = CN - pi.dot(N)
CN_barre

for elem in b_barre:
    print(elem)

b_barre[1][0]


[2.]
[4.]
[5.]


4.0

In [138]:
def check_cn(A):
    resp = True
    i_line = 0
    i_col = 0
    elem = 0
    elem_min = A[0][0]
    for i_line,line in enumerate(A):
        for i_elem,elem in enumerate(line):
            if elem < 0 :
                i_line = i_line
                i_col = i_elem
                elem = elem
                resp = False
                if elem < elem_min:
                    elem_min = elem
                
    negative_element = {
        "i_line": i_line,
        "i_col": i_col,
        "elem":elem_min,
        "is_pos": resp
    }
    return negative_element

print(check_cn(CN))
indice_col = check_cn(CN)["i_col"]
indice_col


{'i_line': 0, 'i_col': 1, 'elem': -2, 'is_pos': False}


1

In [101]:
def As_col(A,s):
    col = []
    for elem in A:
        col.append(elem[s])
    return col

As = As_col(N,1)
As_barre = B_inv.dot(As)
As_barre

array([2., 2., 1.])

In [102]:
def check_As(As):
    resp = True
    for line in As:
        if line < 0:
            resp = False
            break
    return resp

check_As(As_barre)

True

In [139]:
def calcul_xs(b, a):
    xs_tab = []
    for i in range(len(b)):
        xs = b_barre[i][0] / As_barre[i]
        xs_tab.append(xs)
    
    return xs_tab

def min_xs(t):
    indice = 0
    elem_min = t[0]
    for index, element in enumerate(t):
        if (element < elem_min) and (element > 0):
            elem_min = element
            indice = index
    
    return {
        "indice": indice,
        "elem_min": elem_min
    }


In [104]:
add_col = np.array(As)

As_col = np.array(As)

def at_col(M,indice):
    at_col = []
    for i in range(len(M)):
        at_col.append(M[i][indice])
    return at_col

At_col = np.array(at_col(B,0))
        
B_d = np.delete(B, 1, axis=1)
B_a = np.insert(B_d, 1, As_col, axis=1)
B_a

#def permute_col():
    

array([[1, 2, 0],
       [0, 2, 0],
       [0, 1, 1]])

In [152]:
def new_base(B, As,i):
    As_col = np.array(As)
    #At_col = np.array(at_col(B,i)) 
    B_d = np.delete(B, i, axis=1)
    B_a = np.insert(B_d, i, As_col, axis=1)
    return B_a
    
def new_N(B, N, i, indice_col):
    #As_col = np.array(As)
    At_col = np.array(at_col(B,i)) 
    N_d = np.delete(N, indice_col, axis=1)
    N_a = np.insert(N_d, indice_col, At_col, axis=1)
    return N_a

#new_N = new_N(N, As, At_col, 0)
x = calcul_xs(b_barre, As_barre)
ind = min_xs(x)["indice"]

new_b = new_base(B, As, ind)
new_n = new_N(B, N,ind, indice_col)
new_n

array([[-3,  1],
       [-1,  0],
       [ 1,  0]])

In [172]:
def new_CN(cn, cb, s_cn, ind_cb):
    cn_d = np.delete(cn, s_cn, axis=1)
    c_a = np.insert(cn_d, s_cn, cb[0][ind_cb], axis=1)
    return c_a

def new_CB(cn, cb, s_cn, ind_cb):
    cb_d = np.delete(cb, ind_cb, axis=1)
    cb_a = np.insert(cb_d, ind_cb, cn[0][s_cn], axis=1)
    return cb_a
    
n_cn = new_CN(CN, CB, 1, 0)
n_cb = new_CB(CN, CB, 1, 0)
n_cb

array([[-2,  0,  0]])

In [1]:
2/-1


-2.0