In [186]:
import re
import numpy as np

target_function = "5*x1 -3*x2"
constraints = "2*x1 -3*x2 +9*x4 >= 4\n3*x1 +5*x2 -6*x4 <= 6\n1*x1 -7*x2 +10*x3 <= 1"
constraint_one_by_one = constraints.split('\n')

pattern = r'([+-]?\d+)\s*\*?\s*([a-zA-Z0-9]+)\s*([<>]=?|==)\s*([+-]?\d+)'

coeff_regex = r'([+-]?\d+)\s*\*?\s*([a-zA-Z0-9]+)\s*'
signe_regex = r'([<>]=?|==)\s*([+-]?\d+)'

target_catcher = re.findall(coeff_regex, target_function)
target_coeff = [int(match[0]) for match in target_catcher]
    
print(target_coeff)
tab = [1,2,3]
target_coeff += [0] * count_sign(signe_tab)

print(target_coeff)

coeff_tab = []
variables_tab = []
signe_tab = []
const_tab = []

In [ ]:
def target_standard_form(taget_function):
    pass

In [ ]:
def constrain_split(constraints):
    constraint_one_by_one = constraints.split('\n')
    coeff_regex = r'([+-]?\d+)\s*\*?\s*([a-zA-Z0-9]+)\s*'
    signe_regex = r'([<>]=?|==)\s*([+-]?\d+)'
    coeff_tab = []
    variables_tab = []
    signe_tab = []
    const_tab = []
    
    for constraint in constraint_one_by_one:
        coeff_catcher = re.findall(coeff_regex, constraint)
        signe_catcher = re.findall(signe_regex, constraint)
        coefficients = [int(match[0]) for match in coeff_catcher]
        variables = [match[1] for match in coeff_catcher]
        coeff_tab.append(coefficients)
        variables_tab.append(variables)
        signe = [match[0] for match in signe_catcher]
        #signe = signe_catcher[0]

        constant = [int(match[1]) for match in signe_catcher]
        signe_tab.append(signe)
        const_tab.append(constant)
        
    output = {
        "coefficients": coeff_tab,
        "variables": variables_tab,
        "signes": signe_tab,
        "constantes": const_tab
    }
    

In [187]:
for constraint in constraint_one_by_one:
    coeff_catcher = re.findall(coeff_regex, constraint)
    signe_catcher = re.findall(signe_regex, constraint)
    coefficients = [int(match[0]) for match in coeff_catcher]
    variables = [match[1] for match in coeff_catcher]
    coeff_tab.append(coefficients)
    variables_tab.append(variables)
    signe = [match[0] for match in signe_catcher]
    #signe = signe_catcher[0]

    constant = [int(match[1]) for match in signe_catcher]
    signe_tab.append(signe)
    const_tab.append(constant)

In [188]:
print(coeff_tab)
print(variables_tab)     

print(signe_tab)
print(const_tab)

print(constraints)
print(constraint_one_by_one[0])

[[2, -3, 9], [3, 5, -6], [1, -7, 10]]
[['x1', 'x2', 'x4'], ['x1', 'x2', 'x4'], ['x1', 'x2', 'x3']]
[['>='], ['<='], ['<=']]
[[4], [6], [1]]
2*x1 -3*x2 +9*x4 >= 4
3*x1 +5*x2 -6*x4 <= 6
1*x1 -7*x2 +10*x3 <= 1
2*x1 -3*x2 +9*x4 >= 4


In [189]:
print(signe_tab[2][0])
A = np.array(coeff_tab)
print("A = \n",A)
def count_sign(tab):
    cpt=0
    for sign in tab:
        if sign[0] == '<=' or sign[0] == '>=' or sign[0] == '>' or sign[0] == '<':
            cpt = cpt + 1
    return cpt

nbr_sign = count_sign(signe_tab)
print("nbr_sign = ", nbr_sign)

def add_zero(M, nbr_col):
    number_rows = M.shape[0]
    zero_array = np.zeros((number_rows, nbr_col))
    new_array = np.hstack((M, zero_array))
    return new_array

new_arr = add_zero(A, nbr_sign)
print("new_array =\n", new_arr)
print(new_arr[0][-3])

for a in enumerate(signe_tab):
    print(a[1][0])
    #i = signe_tab.index(a)
    i = a[0]
    print("i = ",i)
    if a[1][0] == '<' or a[1][0] == '<=':
        new_arr[i][-nbr_sign] = 1
        nbr_sign -= 1
    elif a[1][0] == '>' or a[1][0] == '>=':
        new_arr[i][-nbr_sign] = -1
        nbr_sign -= 1
    print(new_arr[i])
    
print("new new_array = \n", new_arr)
        

<=
A = 
 [[ 2 -3  9]
 [ 3  5 -6]
 [ 1 -7 10]]
nbr_sign =  3
new_array =
 [[ 2. -3.  9.  0.  0.  0.]
 [ 3.  5. -6.  0.  0.  0.]
 [ 1. -7. 10.  0.  0.  0.]]
0.0
>=
i =  0
[ 2. -3.  9. -1.  0.  0.]
<=
i =  1
[ 3.  5. -6.  0.  1.  0.]
<=
i =  2
[ 1. -7. 10.  0.  0.  1.]
new new_array = 
 [[ 2. -3.  9. -1.  0.  0.]
 [ 3.  5. -6.  0.  1.  0.]
 [ 1. -7. 10.  0.  0.  1.]]
